name: "Publish"
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish CLI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Detect and Tag New Version
        uses: salsify/action-detect-and-tag-new-version@v2.0.1

      - run: npm install
      - run: node scripts/publish.js ${{ secrets.NPM_AUTH_TOKEN }}
