name: "Publish"
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish CLI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install -g @jsdevtools/npm-publish
      - run: npm install
      - run: npm-publish --token ${{ secrets.NPM_AUTH_TOKEN }}
